---
title: "Spatial Viz"
---

```{r}
#load libraries
library(tidyverse)
library(openintro)
library(sf)
library(maps)
library(leaflet)
library(gplots)
library(mosaic)
```


```{r}
# Import starbucks  data
starbucks <- read.csv("https://mac-stat.github.io/data/starbucks.csv")
states_map <- map_data("state")
starbucks_us_by_state <- starbucks |>
  filter(Country == "US") |>
  count(State.Province) |>
  mutate(state_name = str_to_lower(abbr2state(State.Province)))
census_pop_est_2018 <- read_csv("https://mac-stat.github.io/data/us_census_2018_state_pop_est.csv") |>
  separate(state, into = c("dot", "state"), extra = "merge") |>
  select(-dot) |>
  mutate(state = str_to_lower(state))
starbucks_with_2018_pop_est <-
  starbucks_us_by_state |>
  left_join(census_pop_est_2018,
    by = c("state_name" = "state")
  ) |>
  mutate(starbucks_per_10000 = (n / est_pop_2018) * 10000)
starbucks_contiguous_us <- starbucks |>
  filter(Country == "US", State.Province != "AK", State.Province != "HI")

#Creating map of Starbucks locations, and density of Starbucks per population
#| fig-alt: "Map of Starbucks locations in the United States. Most are concentrated on the West Coast, with a lot existing in major cities across the US. The least amount of Starbucks are in the South."
ggplot(starbucks_with_2018_pop_est) +
  geom_map(map = states_map, aes(map_id = state_name, fill = starbucks_per_10000)) +
  expand_limits(x = states_map$long, y = states_map$lat) +
  theme_map() +
  scale_fill_gradientn(name = "Starbucks Per 10000 People", colors = c("darkgreen", "green", "lightgreen"), values = scales::rescale(seq(0, 100, by = 5))) +
  geom_point(
    data = starbucks_contiguous_us,
    aes(x = Longitude, y = Latitude),
    alpha = 0.3, size = 0.2, color = "blue"
  ) +
  theme_map() +
  labs(title = "Density of Starbucks' in the United States", 
       caption = "Source from Github, By Colette Lawler")
```
