---
title: "Exam 1"
format: html
---

```{r}
library(tidytuesdayR)
library(tidyverse)
food_consumption <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2020/2020-02-18/food_consumption.csv')
fc <- food_consumption

```


```{r}
world_map <- map_data("world")

#| fig-cap: "10 maps of the world with food consumption in kilograms per person per year for food categories of beef, eggs, fish, lamb and goat, milk, nuts, pork, poultry, rice, soybeans, and wheat. Milk and wheat has the most overall consumption in the world." 

ggplot(fc, aes(map_id = country, fill = consumption)) +
  geom_map(map = world_map) +
  expand_limits(x = world_map$long, y = world_map$lat) +
  facet_wrap(~food_category) +
  labs(x = "", y = "",
       title = "Food Consumption per Country by Food Category",
       caption = "Source: Tidy Tuesday, Visualization by Colette Lawler") +
  scale_fill_gradientn(name = "Consumption: kg/person/year", colors = c("lightblue", "blue", "darkblue"))


```

