---
title: "Exam 2"
format: html
---

```{r}
library(tidytuesdayR)
library(tidyverse)
library(rnaturalearth) 
library(sf)

tuesdata <- tt_load('2020-02-18')
fc <- tuesdata$food_consumption

str(fc)

head(fc, 22)
```
```{r}
fcc <-
fc |>
  mutate(food_category = fct_recode(food_category, 
         "Lamb" = "Lamb & Goat",
         "Dairy" = "Milk - inc. cheese",
         "Wheat" = "Wheat and Wheat Products", 
         "Nuts" = "Nuts inc. Peanut Butter"
                          )) 
```



1.  Which 5 countries consume the most food?

```{r}
fcc |>
  group_by(country) |>
  summarize(sum = sum(consumption)) |>
  arrange(desc(sum)) |>
  head(5)
```

```{r}
fc |>
  group_by(country) |>
  summarize(sum = sum(consumption)) |>
  arrange(desc(sum)) |>
  head(5) |>
ggplot(aes(x = country, y = sum)) +
  geom_col() +
  labs(x = "Country", y = "Food Consumption")
```
2. Which top 5 countries consume each food?

```{r}
fc |>
  select(food_category, country, consumption) |>
   group_by(food_category) |>
  slice_max(consumption, n = 5)
```


```{r}
fc |>
  select(food_category, country, consumption) |>
  group_by(food_category) |>
  slice_max(consumption, n = 5) |>
ggplot(aes(x = country, y = consumption)) +
geom_col() +
  facet_wrap(~food_category) +
  labs(x = "Country", y = "Consumption")
```

3. What does the consumption of each food look like?

```{r}
ne_countries(returnclass = "sf") |>
  select(name, geometry) |>
  mutate(name = ifelse(name == "United States of America", "USA", name)) |>
  mutate(name = ifelse(name == "Bosnia and Herz.", "Bosnia and Herzegovina", name)) |>
  mutate(name = ifelse(name == "Czechia", "Czech Republic", name)) |> 
  mutate(name = ifelse(name == "Taiwan", "Taiwan. ROC", name)) |>
  left_join(
    fcc |>
      select(-co2_emmission) |>
      group_by(food_category) |>
      mutate(consumption = (consumption - mean(consumption))/sd(consumption)),
    by = c("name" = "country")
  ) |>
  pivot_wider(names_from = food_category, values_from = consumption) |>
  select(-"NA") |>  
  pivot_longer(cols = c(-name, -geometry), names_to = "food_category", values_to = "consumption") |>
  ggplot() +
  geom_sf(aes(fill = consumption), color = "black", size = 0.2) +  
  scale_fill_viridis_c(option = "B", direction = 1, na.value = "gray") +  
  facet_wrap(~food_category) +
  labs(
    title = "Food Consumption by Country",
    fill = "Consumption",
    caption = "Visualization by Colette Lawler"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom",
        strip.text = element_text(size = 10),
        panel.spacing = unit(1, "lines"))
```

```
```{r}

```

